# Generated by Django 5.2.4 on 2025-12-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Descricao'),
        ),
    ]
